name: Keep Render App Alive
on:
  schedule:
    - cron: "*/15 * * * *" # Runs every 15 minutes
  workflow_dispatch: # Enable manual runs
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: curl -s https://chess-game-ak2j.onrender.com > /dev/null
